### PR TITLE
Move 1149v4

### PR DESCRIPTION
**Pull request by imadsyed333**
# Issue Addressed
Part of MOVE-1194

# Description
You can now hover over any part of the row, and the corresponding map pin will be highlighted.

image

# Tests
Tested in MOVE local v1.12.0 using Firefox

### CODE REVIEW

**Comment by lowsound42** [comment]
image

I think we have the same problem here with multiple calls being made @imadsyed333, presumably this is still coming from the watcher.

**Review by lowsound42 — CHANGES_REQUESTED** [review]
Still seeing the same issues with repeated calls going to the API on hover requests.

**Comment by lowsound42** [comment]
sorry to be nitpicky about this again 😬 , but it seems to be the watcher in the FcMapPopup again 
image

If you take the deep check out of there, the repeated calls stop. I actually think this was in the last PR not specifically this one, but it is dealing with the same issue.

**Comment by imadsyed333** [comment]
> sorry to be nitpicky about this again 😬 , but it seems to be the watcher in the FcMapPopup again image
> 
> If you take the deep check out of there, the repeated calls stop. I actually think this was in the last PR not specifically this one, but it is dealing with the same issue.

@lowsound42 I think my latest change solves it (it has on my end). I noticed that featureKey was computed based off the layer name and the id of the selected / hovered feature. However, the map pins all had undefined id, so featureKey never changed whenever you clicked or hovered between map pins, so the popup content was not being rendered. I added some logic to provide the featureKey with the centrelineId instead, so featureKey now changes when moving between map pins, and the watcher will get activated appropriately.

**Comment by lowsound42** [comment]
> > sorry to be nitpicky about this again 😬 , but it seems to be the watcher in the FcMapPopup again image
> > If you take the deep check out of there, the repeated calls stop. I actually think this was in the last PR not specifically this one, but it is dealing with the same issue.
> 
> @lowsound42 I think my latest change solves it (it has on my end). I noticed that featureKey was computed based off the layer name and the id of the selected / hovered feature. However, the map pins all had undefined id, so featureKey never changed whenever you clicked or hovered between map pins, so the popup content was not being rendered. I added some logic to provide the featureKey with the centrelineId instead, so featureKey now changes when moving between map pins, and the watcher will get activated appropriately.

amazing, yeah, this looks like it's working 👍🏽

**Review by lowsound42 — APPROVED** [review]

**Pull request merged**
