### PR TITLE
Move 1225v2

### PR DESCRIPTION
**Pull request by spencermountain**
# Issue Addressed
This PR closes:
* [MOVE-1176](https://move-toronto.atlassian.net/browse/MOVE-1176) - Webapp should be more responsive
* [MOVE-1210](https://move-toronto.atlassian.net/browse/MOVE-1210) - POI chips should display information on hover-over
* [MOVE-1170](https://move-toronto.atlassian.net/browse/MOVE-1170) - Search bar should have a clear button (x)
* [MOVE-1173](https://move-toronto.atlassian.net/browse/MOVE-1173) - Reports page: bring back map peek ability

it's a follow-up with fixes from #1225  - notably, it splits `<FcListLocationMulti` into two componenents, so they can be styled differently in the view-data component.

# Description
* changes **view report** caret buttons to secondary, so they're clearer
* adds tooltips to new buttons
* only show filter fraction numbers if numerator+denomintor are different
* turn collision details table into a html table, so it will copy+paste into excel properly
* moves omar's new location-menu into top-bar in collision report
* fixes POI tooltips not showing up in floating sidebar
* small styling tweaks for expansion panels

### CODE REVIEW

**Comment by lowsound42** [comment]
It seems like linking back to a multi location collision report throws a 500 on this branch @spencermountain, not sure why. I'm just comparing to master to see what changes may have caused that and I'll post here.

**Comment by spencermountain** [comment]
@lowsound42 ya i noticed that too. i really only changed the dropdown html. Didn't touch the backend, or make any new calls.

**Comment by lowsound42** [comment]
> @lowsound42 ya i noticed that too. i really only changed the dropdown html. Didn't touch the backend, or make any new calls.

yeah its weird, not sure why its doing this. Just digging a bit.

**Comment by lowsound42** [comment]
im a dummy, found it. It was a weird merge issue that probably would be resolved when you put this back into master. I added a conditional check here that isnt in your branch to account for this. Kind of forgot about it. It's in master so it should be fine when you merge in.

image

**Comment by lowsound42** [comment]
image
:chefs kiss:

**Review by lowsound42 — APPROVED** [review]
Looks great. Merge into master should fix the backlink issue since that was added after the most recent sync to master for this branch.

**Pull request merged**
