### PR TITLE
MOVE-1189   After editing the location of a request, other study values switch to defaults

### PR DESCRIPTION
**Pull request by ryanpdaley**
# Issue Addressed
"This PR closes [MOVE-1189](https://move-toronto.atlassian.net/browse/MOVE-1189) - After editing the location of a request, other study values switch to defaults

# Description
If the new location is 'compatible' with the current study request, all that will change is the location.
If not, a modal will appear informing the user of this:
image

# Tests
All tests are passing.

### CODE REVIEW

**Comment by lowsound42** [comment]
Looks good when you move from midblock to intersection (and vice versa) when the study selection is the default. i.e., if you are on a midblock with a SVC and you switch, the popup shows up and you then move to the new location with a blank study type. But if we were on a midblock on a TMC for instance, we receive the same popup telling us that the study type doesn't exist, and then we move to the new location keeping the study type as TMC. It seems like it may be a bit confusing. Would it make sense to just make the study type blank regardless of whether it exists or not so that the user reads the popup and has to make the change as suggested?

Eg: 
image
We're on a midblock on a TMC study. I want to switch to an intersection.
image
This is a bit confusing because TMC's should be valid.

image
The change is made and the studytype remains valid. 

For this user flow the popup seems to be an extra step that may add confusion and complexity? That's just my initial impression.

**Comment by ryanpdaley** [comment]
@lowsound42 - hmm... I'll look into why you are seeing the popup for the TMC... you shouldn't be.

Initially I was playing around with modifying the study request too - I'm currently only updating or not updating the location - but it was like wack-a-mole. If I change the study type, then the times might not be valid, and the 'urgent' info is not contained only in the study request, and the location object in EditStudyLocationPopUp.vue isn't what the study request uses... so I figure that modal + a blank study type was the most direct way of getting a response from the user.

**Comment by lowsound42** [comment]
Yeah this a tricky interaction, I did not enjoy my time with it on that new study request stuff.

**Review by spencermountain — APPROVED** [review]
<borat>very nice!</borat>

**Comment by ryanpdaley** [comment]
image

new modal copy?

**Comment by lowsound42** [comment]
> image
> 
> new modal copy?

yeah that works!

**Review by lowsound42 — APPROVED** [review]

**Pull request merged**
